# Generated by Django 5.1.5 on 2025-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
