# Generated by Django 5.1.5 on 2025-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
