# Generated by Django 5.1.5 on 2025-01-25 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_vendor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='store.order'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=10)),
                ('kind', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=10)),
                ('name', models.CharField(max_length=32)),
                ('address_first_line', models.CharField(max_length=64)),
                ('address_second_line', models.CharField(blank=True, max_length=64, null=True)),
                ('pincode', models.IntegerField()),
                ('phone', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'city', 'kind', 'name', 'pincode')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.address'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
