#!/bin/sh

python manage.py collectstatic --noinput
# pip install pillow
python manage.py makemigrations
python manage.py migrate
python manage.py loaddata initial_data.json
python manage.py runserver 0.0.0.0:8000