version: "3.9"

services:
  db:
    image: postgres:17
    container_name: db
    volumes:
      - ../db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    env_file:
      - .env.dev
    # build: .
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    volumes:
      - ../:/usr/src/app
    # '/start' is the shell script used to run the service
    command: /start
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    logging:
      driver: "none"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    command: /start-celeryworker
    volumes:
      - ../:/usr/src/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  flower:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    command: /start-flower
    # command: tail -F anything
    volumes:
      - ../:/usr/src/app
    env_file:
      - .env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
