export const ACTION_TYPES = {
  /****** ITEMS *****/
  SET_ITEMS: "SET_ITEMS",
  SET_CATEGORYS: "SET_CATEGORYS",

  /***** VENDOR ******/
  SET_VENDOR_ORDERS: "SET_VENDOR_ORDERS",
  SET_VENDOR_PROFILE: "SET_VENDOR_PROFILE",

  SET_VENDOR_NAME: "SET_VENDOR_NAME",
  SET_VENDOR_ADDRESS: "SET_VENDOR_ADDRESS",
  SET_VENDOR_ADDRESS_PINCODE: "SET_VENDOR_ADDRESS_PINCODE",
  SET_VENDOR_CITY: "SET_VENDOR_CITY",
  SET_VENDOR_STATE: "SET_VENDOR_STATE",
  SET_VENDOR_COUNTRY: "SET_VENDOR_COUNTRY",

  /********COMMON  *****/
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
  SET_NOTIFICATION: "SET_NOTIFICATION",

  /******CART *****/
  SET_CART_ITEMS: "SET_CART_ITEMS",

  /******Ecommerce *****/
  SET_ADDRESS: "SET_ADDRESS",
  RESET_ADDRESS: "RESET_ADDRESS",
};
